# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Nick Setthachayanon
tagline:          ''
description:      'A work in progress.'
paginate:         1
