# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Nick Setthachayanon
tagline:          ''
description:      'A work in progress.'
url:              http://setthachayanon.github.io

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         1

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/lanyon
